#ifndef __RANHTTP_MODULE_REQUEST_PARSER_MACRO_H__
#define __RANHTTP_MODULE_REQUEST_PARSER_MACRO_H__

#ifndef RANHTTP_REQUEST_URL_PATH_SIZE
#define RANHTTP_REQUEST_URL_PATH_SIZE 64
#endif // RANHTTP_REQUEST_URL_PATH_SIZE

#ifndef RANHTTP_REQUEST_PATH_PARAM_NAME_MAX_SIZE
#define RANHTTP_REQUEST_PATH_PARAM_NAME_MAX_SIZE 16
#endif // RANHTTP_REQUEST_PATH_PARAM_NAME_MAX_SIZE

#ifndef RANHTTP_REQUEST_PATH_PARAM_VALUE_BUF_SIZE
#define RANHTTP_REQUEST_PATH_PARAM_VALUE_BUF_SIZE 64
#endif // RANHTTP_REQUEST_PATH_PARAM_VALUE_BUF_SIZE

#ifndef RANHTTP_REQUEST_PATH_PARAM_MAX_COUNT
#define RANHTTP_REQUEST_PATH_PARAM_MAX_COUNT 4
#endif // RANHTTP_REQUEST_PATH_PARAM_MAX_COUNT

#ifndef RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE
#define RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE 16
#endif // RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE

#ifndef RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE
#define RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE 512
#endif // RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE

#ifndef RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT
#define RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT 4
#endif // RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT

#ifndef RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE
#define RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE 64
#endif // RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE

#ifndef RANHTTP_REQUEST_HEADER_VALUE_BUF_SIZE
#define RANHTTP_REQUEST_HEADER_VALUE_BUF_SIZE 128
#endif // RANHTTP_REQUEST_HEADER_VALUE_BUF_SIZE

#ifndef RANHTTP_REQUEST_HEADER_MAX_COUNT
#define RANHTTP_REQUEST_HEADER_MAX_COUNT 32
#endif // RANHTTP_REQUEST_HEADER_MAX_COUNT

#ifndef RANHTTP_REQUEST_COOKIE_MAX_COUNT
#define RANHTTP_REQUEST_COOKIE_MAX_COUNT 8
#endif // RANHTTP_REQUEST_COOKIE_MAX_COUNT

#ifndef RANHTTP_REQUEST_COOKIE_NAME_MAX_SIZE
#define RANHTTP_REQUEST_COOKIE_NAME_MAX_SIZE 64
#endif // RANHTTP_REQUEST_COOKIE_NAME_MAX_SIZE

#ifndef RANHTTP_REQUEST_COOKIE_VALUE_BUF_SIZE
#define RANHTTP_REQUEST_COOKIE_VALUE_BUF_SIZE 128
#endif // RANHTTP_REQUEST_COOKIE_VALUE_BUF_SIZE

#ifndef RANHTTP_REQUEST_PAYLOAD_BUF_SIZE
#define RANHTTP_REQUEST_PAYLOAD_BUF_SIZE 1024
#endif // RANHTTP_REQUEST_PAYLOAD_BUF_SIZE

#ifndef RANHTTP_REQUEST_PAYLOAD_MAX_SIZE
#define RANHTTP_REQUEST_PAYLOAD_MAX_SIZE (RANHTTP_REQUEST_PAYLOAD_BUF_SIZE > 8192 ? RANHTTP_REQUEST_PAYLOAD_BUF_SIZE : 8192)
#else
#if RANHTTP_REQUEST_PAYLOAD_MAX_SIZE < RANHTTP_REQUEST_PAYLOAD_BUF_SIZE
#error "macro RANHTTP_REQUEST_PAYLOAD_MAX_SIZE must be greater than or equal to macro RANHTTP_REQUEST_PAYLOAD_BUF_SIZE"
#endif // RANHTTP_REQUEST_PAYLOAD_MAX_SIZE
#endif // RANHTTP_REQUEST_PAYLOAD_MAX_SIZE

#define RANHTTP_INIT_REQUEST_CONTROL_LIMITS { \
    .max_header_count = RANHTTP_REQUEST_HEADER_MAX_COUNT, \
    .max_path_param_count = RANHTTP_REQUEST_PATH_PARAM_MAX_COUNT, \
    .max_query_param_count = RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT, \
    .max_cookie_count = RANHTTP_REQUEST_COOKIE_MAX_COUNT, \
    .max_payload_size = RANHTTP_REQUEST_PAYLOAD_MAX_SIZE, \
}


#endif // __RANHTTP_MODULE_REQUEST_PARSER_MACRO_H__