#ifndef __RANHTTP_MODULE_REQUEST_PARSER_MACRO_H__
#define __RANHTTP_MODULE_REQUEST_PARSER_MACRO_H__

#include <limits.h>
#include <stdint.h>

#ifndef RANHTTP_REQUEST_READER_BUFFER_SIZE
#define RANHTTP_REQUEST_READER_BUFFER_SIZE 1024
#endif // RANHTTP_REQUEST_READER_BUFFER_SIZE

#if RANHTTP_REQUEST_READER_BUFFER_SIZE < 256 && RANHTTP_REQUEST_READER_BUFFER_SIZE > UINT16_MAX
#error "macro RANHTTP_REQUEST_READER_BUFFER_SIZE must be between 256 and 65535"
#endif // RANHTTP_REQUEST_READER_BUFFER_SIZE < 256 && RANHTTP_REQUEST_READER_BUFFER_SIZE > UINT16_MAX


#ifndef RANHTTP_REQUEST_URL_PATH_SIZE
#define RANHTTP_REQUEST_URL_PATH_SIZE 128
#endif // RANHTTP_REQUEST_URL_PATH_SIZE

#if RANHTTP_REQUEST_URL_PATH_SIZE < 16 && RANHTTP_REQUEST_URL_PATH_SIZE > 4096
#error "macro RANHTTP_REQUEST_URL_PATH_SIZE must be between 16 and 4096"
#endif // RANHTTP_REQUEST_URL_PATH_SIZE < 16 && RANHTTP_REQUEST_URL_PATH_SIZE > 4096

#ifndef RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE
#define RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE 16
#endif // RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE

#if RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE < 1 || RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE > 128
#error "macro RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE must be between 1 and 128"
#endif // RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE < 1 || RANHTTP_REQUEST_QUERY_PARAM_NAME_MAX_SIZE > 128

#ifndef RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE
#define RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE 512
#endif // RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE

#if RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE < 64 || RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE > 4096
#error "macro RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE must be between 64 and 4096"
#endif // RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE < 64 || RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE > 4096

#ifndef RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT
#define RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT 8
#endif // RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT

#if RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT < 1 || RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT > 32
#error "macro RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT must be between 1 and 32"
#endif // RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT < 1 || RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT > 32


#ifndef RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE
#define RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE 64
#endif // RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE

#if RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE < 32 || RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE > 256
#error "macro RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE must be between 32 and 256"
#endif // RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE < 32 || RANHTTP_REQUEST_HEADER_NAME_MAX_SIZE > 256

#ifndef RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE
#define RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE 4096
#endif // RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE

#if RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE < 64 || RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE > 8192
#error "macro RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE must be between 64 and 8192"
#endif // RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE < 64 || RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE > 8192

#ifndef RANHTTP_REQUEST_HEADER_MAX_COUNT
#define RANHTTP_REQUEST_HEADER_MAX_COUNT 32
#endif // RANHTTP_REQUEST_HEADER_MAX_COUNT

#if RANHTTP_REQUEST_HEADER_MAX_COUNT < 1 || RANHTTP_REQUEST_HEADER_MAX_COUNT > 1024
#error "macro RANHTTP_REQUEST_HEADER_MAX_COUNT must be between 1 and 1024"
#endif // RANHTTP_REQUEST_HEADER_MAX_COUNT < 1 || RANHTTP_REQUEST_HEADER_MAX_COUNT > 1024


#ifndef RANHTTP_REQUEST_PAYLOAD_BUF_SIZE
#define RANHTTP_REQUEST_PAYLOAD_BUF_SIZE 1024
#endif // RANHTTP_REQUEST_PAYLOAD_BUF_SIZE

#if RANHTTP_REQUEST_PAYLOAD_BUF_SIZE < 256 || RANHTTP_REQUEST_PAYLOAD_BUF_SIZE > 8192
#error "macro RANHTTP_REQUEST_PAYLOAD_BUF_SIZE must be between 256 and 8192"
#endif // RANHTTP_REQUEST_PAYLOAD_BUF_SIZE < 256 || RANHTTP_REQUEST_PAYLOAD_BUF_SIZE > 8192

#ifndef RANHTTP_REQUEST_PAYLOAD_MAX_SIZE
#define RANHTTP_REQUEST_PAYLOAD_MAX_SIZE (RANHTTP_REQUEST_PAYLOAD_BUF_SIZE > 8192 ? RANHTTP_REQUEST_PAYLOAD_BUF_SIZE : 8192)
#else
#if RANHTTP_REQUEST_PAYLOAD_MAX_SIZE < RANHTTP_REQUEST_PAYLOAD_BUF_SIZE
#error "macro RANHTTP_REQUEST_PAYLOAD_MAX_SIZE must be greater than or equal to macro RANHTTP_REQUEST_PAYLOAD_BUF_SIZE"
#endif // RANHTTP_REQUEST_PAYLOAD_MAX_SIZE
#endif // RANHTTP_REQUEST_PAYLOAD_MAX_SIZE

#define RANHTTP_REQUEST_DEFAULT_LIMITS { \
    .max_header_count = RANHTTP_REQUEST_HEADER_MAX_COUNT, \
    .max_header_value_size = RANHTTP_REQUEST_HEADER_VALUE_MAX_SIZE, \
    .max_query_param_count = RANHTTP_REQUEST_QUERY_PARAM_MAX_COUNT, \
    .max_query_param_value_size = RANHTTP_REQUEST_QUERY_PARAM_VALUE_MAX_SIZE, \
    .max_payload_size = RANHTTP_REQUEST_PAYLOAD_MAX_SIZE, \
    .header_wl = { 0, NULL } \
}


#endif // __RANHTTP_MODULE_REQUEST_PARSER_MACRO_H__