#ifndef __RANHTTP_APP_CONFIG_REQUEST_PARSER_H__
#define __RANHTTP_APP_CONFIG_REQUEST_PARSER_H__

#include "request-parser/@helper.h"

#ifdef RANHTTP_APP_ALLOWED_REQUEST_HEADERS
#undef RANHTTP_APP_ALLOWED_REQUEST_HEADERS
#define RANHTTP_APP_ALLOWED_REQUEST_HEADERS RANHTTP_REQUEST_PARSER_ALLOWED_REQUEST_HEADERS()
#else
#define RANHTTP_APP_ALLOWED_REQUEST_HEADERS RANHTTP_REQUEST_PARSER_ALLOWED_REQUEST_HEADERS( \
        "X-Requested-With", \
        "X-HTTP-Method-Override", \
        "X-HTTP-Method", \
        "X-HTTP-Version" \
    )
#endif // RANHTTP_APP_ALLOWED_REQUEST_HEADERS


#ifdef RANHTTP_APP_ALLOWED_RESPONSE_HEADERS
#undef RANHTTP_APP_ALLOWED_RESPONSE_HEADERS
#define RANHTTP_APP_ALLOWED_RESPONSE_HEADERS RANHTTP_REQUEST_PARSER_ALLOWED_RESPONSE_HEADERS()
#else
#define RANHTTP_APP_ALLOWED_RESPONSE_HEADERS RANHTTP_REQUEST_PARSER_ALLOWED_RESPONSE_HEADERS()
#endif // RANHTTP_APP_ALLOWED_RESPONSE_HEADERS

#endif // __RANHTTP_APP_CONFIG_REQUEST_PARSER_H__